imports:
    - { resource: "@LocasticSyliusComparerPlugin/Resources/config/parameters.yml" }
    - { resource: "@LocasticSyliusComparerPlugin/Resources/config/services.yml" }
    - { resource: "@LocasticSyliusComparerPlugin/Resources/config/resources.yml" }

sylius_ui:
    events:
        sylius.shop.layout.header:
            blocks:
                javascripts:
                    template: "@LocasticSyliusComparerPlugin/_stylesheets.html.twig"
                    priority: 10
